# Simple workflow for deploying static content to GitHub Pages
name: Dev sandbox workflow

on:
    # Allows us to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true
            - name: Move HTML to dist
              run: ./bundle.bash
